name: M

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./packages/python
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: PATH setup
        run: |
          echo "./packages/bash/lib" >> $GITHUB_PATH
          pip install typing_extensions pycodestyle pylint mypy wemake-python-styleguide flake8 coverage bandit==1.7.2
      - name: Checks
        run: |
          ./m/scripts/checks/ci.sh
      - name: Publish
        run: |
          ./m/scripts/publish.sh
