name: M

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./packages/python
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: PATH setup
        run: |
          echo "./packages/bash/lib" >> $GITHUB_PATH
      - name: M Environment
        run: |
          m ci env m
          cat m/.m/env.list
