name: M

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ./packages/python
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: PATH setup
        run: |
          echo "./packages/bash/lib" >> $GITHUB_PATH
          pip install typing_extensions pycodestyle pylint
      - name: Checks
        run: |
          ./build/build.sh
      - name: Publish
        run: |
          ./build/publish.sh
